appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: BH/+EB0KntsA3XeZVpI8NFMONfIcgMFDbQJ8m2mgwVMsR7V9inkbBRRJ8Y712B3POsKAKKs1yEhi4SGfJQJIBDo+Ly4S4DYCUCc+ni1jrlg2bvKVgihMe9N0Kzp86XWX8Yboi6u0UDhQfWZikkdu7sfhm3vgSbpEmbhOcHXfqSAR1raBA3419qEf0/F/PiIXqSiI5Yhp84wU3mB1XZilx6Hs0EkY1iUfY8jhQIyaAxTOcWvEiNfK8dnWJLpZRdmD2dC9xaxbwVofehgnASJvexmdiGbG7EhkhMp1jJCESpuY32hQpLEPVfka3OT95I0ArHiNU+g9Utg9vPAWLIijrcFpDJ10zaBXYjQiEpAah3g0Tm/vqjFJHkxnbmK+3ml1/xAqdGbxkylF/SmAn6bVVegIvyXUwplLMJYf8rzrE9rogaXOm2uYq5Ow6avIeWMrQ6EYMcwuFttKKANMsBfvxnjmPGEPvUlP19GCaUQYfK1qtnW4oYlO6BWuSwv0pK3503VAibncSXLJaZS5e+YAwOxXqOar4AYDzPJfitoBueGWG02tNlvLg8lCaX40SJPl6SNBVqZqtW/3Lv2PO9gNquPFudVNjAhWxdjvz7lH75/9RkX5ELmiQ1MBqUDL8EGWOdC1LADOadDSAFJHWvzmSLpVtPbQvX4B3mVJDoJBqeA=}
